# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hijup' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hijup

  target 'hijup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hijupTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

